### PR TITLE
Updated dependencies to 1.3.x

### PR DESCRIPTION
**Pull request by PLNech**
I used your (very useful) directive in a 1.3.15 angular project, and found no problem with this version as far as I know.

### CODE REVIEW

**Comment by PLNech** [comment]
I added my name in the authors per reflex while forking, but considering the emptiness of this contribution fell free to remove it until I contribute seriously to your directive :)

**Comment by ghostbar** [comment]
Awesome, thanks a lot. This actually counts a lot as a contribution.

**Comment by Rakku** [comment]
Well thank you, I'm glad I helped !

**Comment by PLNech** [comment]
Well thank you, I'm glad I could help !

**Pull request merged**
